# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow_pitch_joint_left:
    has_acceleration_limits: true
    max_acceleration: 0.5
  elbow_pitch_joint_right:
    has_acceleration_limits: true
    max_acceleration: 0.5
  elbow_roll_joint_left:
    has_acceleration_limits: true
    max_acceleration: 0.5
  elbow_roll_joint_right:
    has_acceleration_limits: true
    max_acceleration: 0.5
  shoulder_pitch_joint_left:
    has_acceleration_limits: true
    max_acceleration: 0.2
  shoulder_pitch_joint_right:
    has_acceleration_limits: true
    max_acceleration: 0.2
  shoulder_roll_joint_left:
    has_acceleration_limits: true
    max_acceleration: 0.3
  shoulder_roll_joint_right:
    has_acceleration_limits: true
    max_acceleration: 0.3
  shoulder_yaw_joint_left:
    has_acceleration_limits: true
    max_acceleration: 0.2
  shoulder_yaw_joint_right:
    has_acceleration_limits: true
    max_acceleration: 0.2
  torso_joint:
    has_acceleration_limits: true
    max_acceleration: 0.07
  wrist_pitch_joint_left:
    has_acceleration_limits: true
    max_acceleration: 0.5
  wrist_pitch_joint_right:
    has_acceleration_limits: true
    max_acceleration: 0.5
  wrist_yaw_joint_left:
    has_acceleration_limits: true
    max_acceleration: 0.5
  wrist_yaw_joint_right:
    has_acceleration_limits: true
    max_acceleration: 0.5
